### ISSUE TITLE
configure exception if not using multitenancy option

### ISSUE THREAD

**Issue by scharada** [johnknoop/MongoRepository#14]
hi
i am trying to use a database (not multitenant) using the service extension method
'MongoRepository.Configure()
                .Database("Accounting-DB", db => db
                    .Map<col1>("colname1")
                    .Map<col2>("colname2")
                    .MapAlongWithSubclassesInSameAssebmly<BaseEntity>("col3", x => x
                        .WithIdProperty(baseentity => baseentity.Id)
                        .WithIndex(baseentity => baseentity.uniqueaddress , unique: true)
                    )
                )
                .Build();'

this throws an error  in the AddRepoMethod: here is a screenshot 
![image](https://user-images.githubusercontent.com/1780858/83774657-431ca280-a686-11ea-9329-13230f26c216.png)

**Comment by johnknoop** [comment]
Hi @scharada and thanks for reporting this.

Not using multitenancy at all is frankly a scenario I haven't even considered, since that was (at least initially) the main reason for creating this library.

I can have a look at it and make sure it handles the scenario where there is no tenant key present in the service provider, but it might take a few days since I'm only doing this on my spare time.

**Comment by scharada** [comment]
@johnknoop  that would be great. 
while we are here i have a question:
if i take the example in the doc, does that make the employee common to all databases and db operations are routed to the shared db ?

if that's the case, it is an incomplete scenario and here is why:
in a multitenant db, the company that owns the SaaS business has its own employees and each of the tenants can have his own employees too.

the library should handle different strategies:
Separate Database
Separate Schema
Shared Schema
and on top of that , if we can tag entities to set their behavior as follows :   
1 - SharedOnly: exists in gloobal db only
2 - TenantOnly : exists in Tenant Db Only
3 - SharedAndTenant : exists in both global and tenant databases. in this case a mechanism for switching database at the query level should exists to make calls against the right DB/collection. this is usually handeled using UoW or by creating 2 separate repository interfaces (less desirable).
this would make the library able to handle any multitenant scenario.

**Comment by johnknoop** [comment]
In the example, the `Employee` type is mapped in the 'HeadOffice' database, which in turn is mapped using the `.Database` method, as opposed to the `.DatabasePerTenant` method.

When you map a database using the `.DatabasePerTenant` method, then all types mapped under that database will be written to and read from a database with the tenant key prefixed in the name.

So in the example of the zoo.. If we play with the idea that we have two tenants: "LondonZoo" and "MoscowZoo", then the database structure will look like this:

```
Headoffice // database
     └─ Employee // collection
LondonZoo_Zoo // database
      ├─ AnimalKeeper // collection
      ├─ Enclosures // collection
      └─ Animals // collection
MoscowZoo_Zoo // database
      ├─ AnimalKeeper // collection
      ├─ Enclosures // collection
      └─ Animals // collection
```

There are many different ways of doing multitenancy. This library only supports the "database per tenant" pattern.

**Comment by scharada** [comment]
@johnknoop have you had a chance to make the above change ?

**Comment by scharada** [comment]
> I can have a look at it and make sure it handles the scenario where there is no tenant key present in the service provider, but it might take a few days since I'm only doing this on my spare time.

@johnknoop have you had a chance to make the above change ?

**Comment by johnknoop** [comment]
@scharada Sorry I haven't gotten around to it yet. I'll try to find time for it in the coming days.

**Comment by johnknoop** [comment]
@scharada I don't wanna keep you waiting for this. I have so much stuff on my plate now, both at work and with evening time projects, that I don't see myself being able to free up time for this within the nearest couple of weeks. If you're comfortable waiting a bit longer, then I'll try and get around to it eventually. You're also welcome to make a pull request if you feel like doing it yourself. As a third option, you might wanna consider not using this library at all, since it's pretty easy to accomplish the same thing using the standard mongo driver, especially if you don't want the multitenancy feature.

**Comment by scharada** [comment]
@johnknoop i managed to fix that. will send you the changes if you want to incorporate it.
