### ISSUE TITLE
IRepository service not registered.

### ISSUE THREAD

**Issue by scharada** [johnknoop/MongoRepository#27]
System.MissingMethodException: 'Constructor on type 'johnknoop.MongoRepository`1[[MyEntry, assemblyname, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' not found.'

MyEntity is a very simple class with few properties...

the error happens when instantiating a service :
 
```
    public GrpcConfigurationService(ILogger<GrpcConfigurationService> logger , IRepository<MyEntity> repo)
    {
        _logger = logger;
        _repo = repo;

    }

```

here is how i register the repository after configuring the database.

```
// Use reflection to get all entity types
        var entityTypes = Assembly.GetExecutingAssembly().GetTypes()
            .Where(t => t.Namespace == "namespace where entities are" && t.IsClass && !t.IsAbstract);

        foreach (var type in entityTypes)
        {
            // Register the repository for each entity type
            var repositoryType = typeof(IRepository<>).MakeGenericType(type);
            var concreteRepositoryType = typeof(MongoRepository<>).MakeGenericType(type);
            services.AddScoped(repositoryType, serviceProvider => 
                       Activator.CreateInstance(concreteRepositoryType, database)); // << exception happens here
        }

```

what am i doing wrong ??

**Comment by johnknoop** [comment]
Hi @scharada 

I'm not sure that goes wrong without running your code, but there is a Nuget package called [JohnKnoop.MongoRepository.DotNetCoreDi](https://github.com/johnknoop/MongoRepository.DotNetCoreDi) that does exactly what you're trying to do here. You might wanna have a go at that. Instead of looping over all types in a namespace like in your example, it loops over all the types that are mapped (remember you have to [map all your entities](https://github.com/johnknoop/MongoRepository?tab=readme-ov-file#configuration) in order to get things like indices and polymorphism working).
